<?php
defined('BASEPATH') OR exit('No direct script access allowed');


$active_group = 'default';
$query_builder = TRUE;

$db['default'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-AudisisBDC',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_PruebaCliente'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_PruebaCliente',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);


$db['I-Audisis_Andina'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Andina',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Forus'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Forus',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_PFAlimentos'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_PFAlimentos',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_JSC'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_JSC',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_EntelPeru'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_EntelPeru',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_AtentoPeru'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_AtentoPeru',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Wom'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Wom',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Sadia'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Sadia',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_ZTE'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_ZTE',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Sofruco'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Sofruco',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Sika'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Sika',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_DEMOCOMERCIAL'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_DEMOCOMERCIAL',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Durandin'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Durandin',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_Embonor'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_Embonor',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_BredenMaster'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'desarrollo_audisis',
	'password' => 'Audisis_1875_$',
	'database' => 'I-Audisis_BredenMaster',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['Sadia_BBDD'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.210.210',
	'username' => 'castano_ddbb',
	'password' => 'Castano2019$_',
	'database' => 'desarrollo_audisisdia_BBDD',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'desarrollo_audisisve_queries' => TRUE
);

$db['I-Audisis_IST'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'sa',
	'password' => 'Pandora.2016$_%',
	'database' => 'I-Audisis_IST',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['I-Audisis_DIVINUM'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'sa',
	'password' => 'Pandora.2016$_%',
	'database' => 'I-Audisis_Divinum',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);

$db['I-Audisis_Agrosuper'] = array(
	'dsn'	=> '',
	'hostname' => '170.84.209.38',
	'username' => 'sa',
	'password' => 'Pandora.2016$_%',
	'database' => 'I-Audisis_Agrosuper',
	'dbdriver' => 'sqlsrv',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => TRUE,
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);